const airplanes = [
  {
    name: 'mustang',
    id: 1,
    designation: 'P-51',
    variant: 'D',
    fullName: 'P-51D Mustang',
    manufacturer: 'North American Aviation',
    country: 'USA',
    type: 'Fighter',
    role: 'Escort Fighter',
    firstFlight: 1940,
    crew: 1,
    engineCount: 1,
    engine: 'Packard V-1650-7 Merlin',
    horsepower: 1695,
    topSpeed: 437,
    range: 1650,
    wingspan: 37,
    serviceCeiling: 41900
  },

  {
    name: 'superfortress',
    id: 2,
    designation: 'b-29',
    fullName: 'B-29 Superfortress',
    manufacturer: 'Boeing',
    country: 'USA',
    type: 'Bomber',
    role: 'Strategic Bomber',
    firstFlight: 1942,
    crew: 11,
    engineCount: 4,
    engine: 'Wright R-3350',
    horsepower: 2200,
    topSpeed: 357,
    range: 3250,
    wingspan: 141,
    serviceCeiling: 31850
  },

  {
    name: 'spitfire',
    id: 3,
    designation: 'spitfire',
    variant: 'Mk IX',
    fullName: 'Spitfire Mk IX',
    manufacturer: 'Supermarine',
    country: 'UK',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'Rolls-Royce Merlin 61',
    horsepower: 1720,
    topSpeed: 408,
    range: 434,
    wingspan: 36.8,
    serviceCeiling: 43800
  },

  {
    name: 'bf109',
    id: 4,
    designation: 'bf-109',
    variant: 'G',
    fullName: 'Messerschmitt Bf 109 G',
    manufacturer: 'Messerschmitt',
    country: 'Germany',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'DB 605A',
    horsepower: 1455,
    topSpeed: 398,
    range: 528,
    wingspan: 32.5,
    serviceCeiling: 39000
  },

  {
    name: 'corsair',
    id: 5,
    designation: 'f4u-1',
    variant: 'D',
    fullName: 'F4U Corsair',
    manufacturer: 'Vought',
    country: 'USA',
    type: 'Carrier Fighter',
    role: 'Multirole',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney R-2800',
    horsepower: 2250,
    topSpeed: 446,
    range: 1015,
    wingspan: 41,
    serviceCeiling: 41700
  },

  {
    name: 'thunderbolt',
    id: 6,
    designation: 'p-47',
    variant: 'D',
    fullName: 'P-47 Thunderbolt',
    manufacturer: 'Republic Aviation',
    country: 'USA',
    type: 'Fighter',
    role: 'Fighter Bomber',
    firstFlight: 1941,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney R-2800',
    horsepower: 2300,
    topSpeed: 433,
    range: 1800,
    wingspan: 40.9,
    serviceCeiling: 43000
  },

  {
    name: 'zero',
    id: 7,
    designation: 'a6m',
    variant: '2',
    fullName: 'A6M Zero',
    manufacturer: 'Mitsubishi',
    country: 'Japan',
    type: 'Fighter',
    role: 'Carrier Fighter',
    firstFlight: 1939,
    crew: 1,
    engineCount: 1,
    engine: 'Nakajima Sakae',
    horsepower: 940,
    topSpeed: 331,
    range: 1930,
    wingspan: 39.4,
    serviceCeiling: 33000
  },

  {
    name: 'flyingFortress',
    id: 8,
    designation: 'b-17',
    variant: 'G',
    fullName: 'B-17 Flying Fortress',
    manufacturer: 'Boeing',
    country: 'USA',
    type: 'Bomber',
    role: 'Heavy Bomber',
    firstFlight: 1935,
    crew: 10,
    engineCount: 4,
    engine: 'Wright R-1820',
    horsepower: 1200,
    topSpeed: 287,
    range: 2000,
    wingspan: 103.8,
    serviceCeiling: 35000
  },

  {
    name: 'lancaster',
    id: 9,
    designation: 'lancaster',
    variant: 'B1',
    fullName: 'Avro Lancaster',
    manufacturer: 'Avro',
    country: 'UK',
    type: 'Bomber',
    role: 'Heavy Bomber',
    firstFlight: 1941,
    crew: 7,
    engineCount: 4,
    engine: 'Rolls-Royce Merlin XX',
    horsepower: 1280,
    topSpeed: 282,
    range: 2530,
    wingspan: 102,
    serviceCeiling: 24000
  },

  {
    name: 'me262',
    id: 10,
    designation: 'me-262',
    variant: 'A',
    fullName: 'Me 262',
    manufacturer: 'Messerschmitt',
    country: 'Germany',
    type: 'Jet Fighter',
    role: 'Interceptor',
    firstFlight: 1942,
    crew: 1,
    engineCount: 2,
    engine: 'Jumo 004',
    horsepower: null,
    topSpeed: 540,
    range: 652,
    wingspan: 41,
    serviceCeiling: 37500
  },

  {
    name: 'lightning',
    id: 11,
    designation: 'p-38',
    fullName: 'P-38 Lightning',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1939,
    crew: 1,
    engineCount: 2,
    engine: 'Allison V-1710',
    horsepower: 1600,
    topSpeed: 414,
    range: 1300,
    wingspan: 52,
    serviceCeiling: 44000
  },

  {
    name: 'bearcat',
    id: 12,
    designation: 'f8f',
    fullName: 'F8F Bearcat',
    manufacturer: 'Grumman',
    country: 'USA',
    type: 'Fighter',
    role: 'Carrier Fighter',
    firstFlight: 1944,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney R-2800',
    horsepower: 2100,
    topSpeed: 421,
    range: 1105,
    wingspan: 35.5,
    serviceCeiling: 38800
  },

  {
    name: 'skyradesignationer',
    id: 13,
    designation: 'a-1',
    fullName: 'A-1 Skyradesignationer',
    manufacturer: 'Douglas',
    country: 'USA',
    type: 'Attack',
    role: 'Close Air Support',
    firstFlight: 1945,
    crew: 1,
    engineCount: 1,
    engine: 'Wright R-3350',
    horsepower: 2700,
    topSpeed: 322,
    range: 1300,
    wingspan: 50,
    serviceCeiling: 28500
  },

  {
    name: 'hurricane',
    id: 14,
    designation: 'hurricane',
    variant: 'Mk I',
    fullName: 'Hawker Hurricane',
    manufacturer: 'Hawker',
    country: 'UK',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1935,
    crew: 1,
    engineCount: 1,
    engine: 'Rolls-Royce Merlin',
    horsepower: 1030,
    topSpeed: 340,
    range: 600,
    wingspan: 40,
    serviceCeiling: 36000
  },

  {
    name: 'tempest',
    id: 15,
    designation: 'tempest',
    variant: 'V',
    fullName: 'Hawker Tempest',
    manufacturer: 'Hawker',
    country: 'UK',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'Napier Sabre',
    horsepower: 2200,
    topSpeed: 432,
    range: 740,
    wingspan: 41,
    serviceCeiling: 37000
  },

  {
    name: 'mosquito',
    id: 16,
    designation: 'mosquito',
    fullName: 'De Havilland Mosquito',
    manufacturer: 'De Havilland',
    country: 'UK',
    type: 'Multirole',
    role: 'Bomber / Recon',
    firstFlight: 1940,
    crew: 2,
    engineCount: 2,
    engine: 'Rolls-Royce Merlin',
    horsepower: 1460,
    topSpeed: 415,
    range: 1500,
    wingspan: 54,
    serviceCeiling: 37000
  },

  {
    name: 'beaufighter',
    id: 17,
    designation: 'beaufighter',
    fullName: 'Bristol Beaufighter',
    manufacturer: 'Bristol',
    country: 'UK',
    type: 'Heavy Fighter',
    role: 'Night Fighter',
    firstFlight: 1939,
    crew: 2,
    engineCount: 2,
    engine: 'Bristol Hercules',
    horsepower: 1735,
    topSpeed: 320,
    range: 1750,
    wingspan: 57,
    serviceCeiling: 29000
  },

  {
    name: 'fw190',
    id: 18,
    designation: 'fw-190',
    fullName: 'Fw 190',
    manufacturer: 'Focke-Wulf',
    country: 'Germany',
    type: 'Fighter',
    role: 'Multirole',
    firstFlight: 1939,
    crew: 1,
    engineCount: 1,
    engine: 'BMW 801',
    horsepower: 1700,
    topSpeed: 408,
    range: 500,
    wingspan: 34.5,
    serviceCeiling: 37000
  },

  {
    name: 'mig15',
    id: 19,
    designation: 'mig-15',
    fullName: 'MiG-15',
    manufacturer: 'Mikoyan-Gurevich',
    country: 'USSR',
    type: 'Jet Fighter',
    role: 'Interceptor',
    firstFlight: 1947,
    crew: 1,
    engineCount: 1,
    engine: 'Klimov VK-1',
    horsepower: null,
    topSpeed: 668,
    range: 745,
    wingspan: 33,
    serviceCeiling: 51000
  },

  {
    name: 'mig21',
    id: 20,
    designation: 'mig-21',
    fullName: 'MiG-21',
    manufacturer: 'Mikoyan-Gurevich',
    country: 'USSR',
    type: 'Jet Fighter',
    role: 'Interceptor',
    firstFlight: 1955,
    crew: 1,
    engineCount: 1,
    engine: 'Tumansky R-25',
    horsepower: null,
    topSpeed: 1386,
    range: 760,
    wingspan: 23.5,
    serviceCeiling: 59000
  },

  {
    name: 'mig29',
    id: 21,
    designation: 'mig-29',
    fullName: 'MiG-29',
    manufacturer: 'Mikoyan',
    country: 'Russia',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1977,
    crew: 1,
    engineCount: 2,
    engine: 'RD-33',
    horsepower: null,
    topSpeed: 1490,
    range: 890,
    wingspan: 37,
    serviceCeiling: 59000
  },

  {
    name: 'su27',
    id: 22,
    designation: 'su-27',
    fullName: 'Su-27',
    manufacturer: 'Sukhoi',
    country: 'Russia',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1977,
    crew: 1,
    engineCount: 2,
    engine: 'AL-31F',
    horsepower: null,
    topSpeed: 1550,
    range: 2200,
    wingspan: 48,
    serviceCeiling: 62000
  },

  {
    name: 'phantom',
    id: 23,
    designation: 'f-4',
    fullName: 'F-4 Phantom II',
    manufacturer: 'McDonnell Douglas',
    country: 'USA',
    type: 'Fighter',
    role: 'Multirole',
    firstFlight: 1958,
    crew: 2,
    engineCount: 2,
    engine: 'J79',
    horsepower: null,
    topSpeed: 1473,
    range: 1600,
    wingspan: 38.5,
    serviceCeiling: 60000
  },

  {
    name: 'tomcat',
    id: 24,
    designation: 'f-14',
    fullName: 'F-14 Tomcat',
    manufacturer: 'Grumman',
    country: 'USA',
    type: 'Fighter',
    role: 'Fleet Defense',
    firstFlight: 1970,
    crew: 2,
    engineCount: 2,
    engine: 'TF30 / F110',
    horsepower: null,
    topSpeed: 1544,
    range: 1800,
    wingspan: 64,
    serviceCeiling: 53000
  },

  {
    name: 'eagle',
    id: 25,
    designation: 'f-15',
    fullName: 'F-15 Eagle',
    manufacturer: 'McDonnell Douglas',
    country: 'USA',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1972,
    crew: 1,
    engineCount: 2,
    engine: 'F100',
    horsepower: null,
    topSpeed: 1650,
    range: 3000,
    wingspan: 42.8,
    serviceCeiling: 65000
  },

  {
    name: 'falcon',
    id: 26,
    designation: 'f-16',
    fullName: 'F-16 Fighting Falcon',
    manufacturer: 'General Dynamics',
    country: 'USA',
    type: 'Fighter',
    role: 'Multirole',
    firstFlight: 1974,
    crew: 1,
    engineCount: 1,
    engine: 'F110',
    horsepower: null,
    topSpeed: 1500,
    range: 2600,
    wingspan: 32.8,
    serviceCeiling: 50000
  },

  {
    name: 'hornet',
    id: 27,
    designation: 'fa-18',
    fullName: 'F/A-18 Hornet',
    manufacturer: 'McDonnell Douglas',
    country: 'USA',
    type: 'Carrier Fighter',
    role: 'Multirole',
    firstFlight: 1978,
    crew: 1,
    engineCount: 2,
    engine: 'F404',
    horsepower: null,
    topSpeed: 1190,
    range: 1275,
    wingspan: 40.4,
    serviceCeiling: 50000
  },

  {
    name: 'yak3',
    id: 28,
    designation: 'yak-3',
    fullName: 'Yak-3',
    manufacturer: 'Yakovlev',
    country: 'USSR',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1943,
    crew: 1,
    engineCount: 1,
    engine: 'Klimov VK-105PF2',
    horsepower: 1290,
    topSpeed: 404,
    range: 404,
    wingspan: 30.2,
    serviceCeiling: 35300
  },

  {
    name: 'la5',
    id: 29,
    designation: 'la-5',
    fullName: 'Lavochkin La-5',
    manufacturer: 'Lavochkin',
    country: 'USSR',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'Shvetsov ASh-82',
    horsepower: 1700,
    topSpeed: 404,
    range: 475,
    wingspan: 32.4,
    serviceCeiling: 36000
  },

  {
    name: 'il2',
    id: 30,
    designation: 'il-2',
    fullName: 'Il-2 Sturmovik',
    manufacturer: 'Ilyushin',
    country: 'USSR',
    type: 'Attack',
    role: 'Ground Attack',
    firstFlight: 1939,
    crew: 2,
    engineCount: 1,
    engine: 'Mikulin AM-38',
    horsepower: 1720,
    topSpeed: 257,
    range: 450,
    wingspan: 48,
    serviceCeiling: 19700
  },

  {
    name: 'pe2',
    id: 31,
    designation: 'pe-2',
    fullName: 'Petlyakov Pe-2',
    manufacturer: 'Petlyakov',
    country: 'USSR',
    type: 'Bomber',
    role: 'Dive Bomber',
    firstFlight: 1939,
    crew: 3,
    engineCount: 2,
    engine: 'Klimov VK-105',
    horsepower: 1100,
    topSpeed: 335,
    range: 720,
    wingspan: 57,
    serviceCeiling: 29000
  },

  {
    name: 'he162',
    id: 32,
    designation: 'he-162',
    fullName: 'Heinkel He 162',
    manufacturer: 'Heinkel',
    country: 'Germany',
    type: 'Jet Fighter',
    role: 'Interceptor',
    firstFlight: 1944,
    crew: 1,
    engineCount: 1,
    engine: 'BMW 003',
    horsepower: null,
    topSpeed: 562,
    range: 606,
    wingspan: 23.6,
    serviceCeiling: 39000
  },

  {
    name: 'do335',
    id: 33,
    designation: 'do-335',
    fullName: 'Dornier Do 335',
    manufacturer: 'Dornier',
    country: 'Germany',
    type: 'Heavy Fighter',
    role: 'Interceptor',
    firstFlight: 1943,
    crew: 1,
    engineCount: 2,
    engine: 'DB 603',
    horsepower: 1750,
    topSpeed: 474,
    range: 720,
    wingspan: 45,
    serviceCeiling: 37500
  },

  {
    name: 'sabre',
    id: 34,
    designation: 'f-86',
    fullName: 'F-86 Sabre',
    manufacturer: 'North American Aviation',
    country: 'USA',
    type: 'Jet Fighter',
    role: 'Air Superiority',
    firstFlight: 1947,
    crew: 1,
    engineCount: 1,
    engine: 'General Electric J47',
    horsepower: null,
    topSpeed: 687,
    range: 1515,
    wingspan: 37.1,
    serviceCeiling: 49000
  },

  {
    name: 'superSabre',
    id: 35,
    designation: 'f-100',
    fullName: 'F-100 Super Sabre',
    manufacturer: 'North American Aviation',
    country: 'USA',
    type: 'Jet Fighter',
    role: 'Fighter Bomber',
    firstFlight: 1953,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney J57',
    horsepower: null,
    topSpeed: 864,
    range: 1995,
    wingspan: 38.8,
    serviceCeiling: 50000
  },

  {
    name: 'starfighter',
    id: 36,
    designation: 'f-104',
    fullName: 'F-104 Starfighter',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Interceptor',
    role: 'High Speed Fighter',
    firstFlight: 1954,
    crew: 1,
    engineCount: 1,
    engine: 'General Electric J79',
    horsepower: null,
    topSpeed: 1456,
    range: 1630,
    wingspan: 21.9,
    serviceCeiling: 58000
  },

  {
    name: 'aardvark',
    id: 37,
    designation: 'f-111',
    fullName: 'F-111 Aardvark',
    manufacturer: 'General Dynamics',
    country: 'USA',
    type: 'Strike Aircraft',
    role: 'Ground Attack',
    firstFlight: 1964,
    crew: 2,
    engineCount: 2,
    engine: 'Pratt & Whitney TF30',
    horsepower: null,
    topSpeed: 1650,
    range: 3700,
    wingspan: 63,
    serviceCeiling: 60000
  },

  {
    name: 'mig23',
    id: 38,
    designation: 'mig-23',
    fullName: 'MiG-23',
    manufacturer: 'Mikoyan',
    country: 'USSR',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1967,
    crew: 1,
    engineCount: 1,
    engine: 'Tumansky R-35',
    horsepower: null,
    topSpeed: 1550,
    range: 1150,
    wingspan: 45,
    serviceCeiling: 61000
  },

  {
    name: 'su25',
    id: 39,
    designation: 'su-25',
    fullName: 'Su-25 Frogfoot',
    manufacturer: 'Sukhoi',
    country: 'USSR',
    type: 'Attack',
    role: 'Close Air Support',
    firstFlight: 1975,
    crew: 1,
    engineCount: 2,
    engine: 'Soyuz R-95',
    horsepower: null,
    topSpeed: 606,
    range: 465,
    wingspan: 47,
    serviceCeiling: 23000
  },

  {
    name: 'thunderboltII',
    id: 40,
    designation: 'a-10',
    fullName: 'A-10 Thunderbolt II',
    manufacturer: 'Fairchild Republic',
    country: 'USA',
    type: 'Attack',
    role: 'Close Air Support',
    firstFlight: 1972,
    crew: 1,
    engineCount: 2,
    engine: 'TF34',
    horsepower: null,
    topSpeed: 439,
    range: 800,
    wingspan: 57.5,
    serviceCeiling: 45000
  },

  {
    name: 'blackbird',
    id: 41,
    designation: 'sr-71',
    fullName: 'SR-71 Blackbird',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Reconnaissance',
    role: 'Strategic Recon',
    firstFlight: 1964,
    crew: 2,
    engineCount: 2,
    engine: 'Pratt & Whitney J58',
    horsepower: null,
    topSpeed: 2193,
    range: 3200,
    wingspan: 55.5,
    serviceCeiling: 85000
  },

  {
    name: 'dragonLady',
    id: 42,
    designation: 'u-2',
    fullName: 'U-2 Dragon Lady',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Reconnaissance',
    role: 'High Altitude Recon',
    firstFlight: 1955,
    crew: 1,
    engineCount: 1,
    engine: 'F118',
    horsepower: null,
    topSpeed: 500,
    range: 6900,
    wingspan: 104,
    serviceCeiling: 70000
  },

  {
    name: 'yak3',
    id: 43,
    designation: 'yak-3',
    fullName: 'Yak-3',
    manufacturer: 'Yakovlev',
    country: 'USSR',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1943,
    crew: 1,
    engineCount: 1,
    engine: 'Klimov VK-105PF2',
    horsepower: 1290,
    topSpeed: 404,
    range: 404,
    wingspan: 30.2,
    serviceCeiling: 35300
  },

  {
    name: 'la5',
    id: 44,
    designation: 'la-5',
    fullName: 'Lavochkin La-5',
    manufacturer: 'Lavochkin',
    country: 'USSR',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'Shvetsov ASh-82',
    horsepower: 1700,
    topSpeed: 404,
    range: 475,
    wingspan: 32.4,
    serviceCeiling: 36000
  },

  {
    name: 'il2',
    id: 45,
    designation: 'il-2',
    fullName: 'Il-2 Sturmovik',
    manufacturer: 'Ilyushin',
    country: 'USSR',
    type: 'Attack',
    role: 'Ground Attack',
    firstFlight: 1939,
    crew: 2,
    engineCount: 1,
    engine: 'Mikulin AM-38',
    horsepower: 1720,
    topSpeed: 257,
    range: 450,
    wingspan: 48,
    serviceCeiling: 19700
  },

  {
    name: 'pe2',
    id: 46,
    designation: 'pe-2',
    fullName: 'Petlyakov Pe-2',
    manufacturer: 'Petlyakov',
    country: 'USSR',
    type: 'Bomber',
    role: 'Dive Bomber',
    firstFlight: 1939,
    crew: 3,
    engineCount: 2,
    engine: 'Klimov VK-105',
    horsepower: 1100,
    topSpeed: 335,
    range: 720,
    wingspan: 57,
    serviceCeiling: 29000
  },

  {
    name: 'he162',
    id: 47,
    designation: 'he-162',
    fullName: 'Heinkel He 162',
    manufacturer: 'Heinkel',
    country: 'Germany',
    type: 'Jet Fighter',
    role: 'Interceptor',
    firstFlight: 1944,
    crew: 1,
    engineCount: 1,
    engine: 'BMW 003',
    horsepower: null,
    topSpeed: 562,
    range: 606,
    wingspan: 23.6,
    serviceCeiling: 39000
  },

  {
    name: 'do335',
    id: 48,
    designation: 'do-335',
    fullName: 'Dornier Do 335',
    manufacturer: 'Dornier',
    country: 'Germany',
    type: 'Heavy Fighter',
    role: 'Interceptor',
    firstFlight: 1943,
    crew: 1,
    engineCount: 2,
    engine: 'DB 603',
    horsepower: 1750,
    topSpeed: 474,
    range: 720,
    wingspan: 45,
    serviceCeiling: 37500
  },

  {
    name: 'sabre',
    id: 49,
    designation: 'f-86',
    fullName: 'F-86 Sabre',
    manufacturer: 'North American Aviation',
    country: 'USA',
    type: 'Jet Fighter',
    role: 'Air Superiority',
    firstFlight: 1947,
    crew: 1,
    engineCount: 1,
    engine: 'General Electric J47',
    horsepower: null,
    topSpeed: 687,
    range: 1515,
    wingspan: 37.1,
    serviceCeiling: 49000
  },

  {
    name: 'superSabre',
    id: 50,
    designation: 'f-100',
    fullName: 'F-100 Super Sabre',
    manufacturer: 'North American Aviation',
    country: 'USA',
    type: 'Jet Fighter',
    role: 'Fighter Bomber',
    firstFlight: 1953,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney J57',
    horsepower: null,
    topSpeed: 864,
    range: 1995,
    wingspan: 38.8,
    serviceCeiling: 50000
  },

  {
    name: 'starfighter',
    id: 51,
    designation: 'f-104',
    fullName: 'F-104 Starfighter',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Interceptor',
    role: 'High Speed Fighter',
    firstFlight: 1954,
    crew: 1,
    engineCount: 1,
    engine: 'General Electric J79',
    horsepower: null,
    topSpeed: 1456,
    range: 1630,
    wingspan: 21.9,
    serviceCeiling: 58000
  },

  {
    name: 'aardvark',
    id: 52,
    designation: 'f-111',
    fullName: 'F-111 Aardvark',
    manufacturer: 'General Dynamics',
    country: 'USA',
    type: 'Strike Aircraft',
    role: 'Ground Attack',
    firstFlight: 1964,
    crew: 2,
    engineCount: 2,
    engine: 'Pratt & Whitney TF30',
    horsepower: null,
    topSpeed: 1650,
    range: 3700,
    wingspan: 63,
    serviceCeiling: 60000
  },

  {
    name: 'mig23',
    id: 53,
    designation: 'mig-23',
    fullName: 'MiG-23',
    manufacturer: 'Mikoyan',
    country: 'USSR',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1967,
    crew: 1,
    engineCount: 1,
    engine: 'Tumansky R-35',
    horsepower: null,
    topSpeed: 1550,
    range: 1150,
    wingspan: 45,
    serviceCeiling: 61000
  },

  {
    name: 'su25',
    id: 54,
    designation: 'su-25',
    fullName: 'Su-25 Frogfoot',
    manufacturer: 'Sukhoi',
    country: 'USSR',
    type: 'Attack',
    role: 'Close Air Support',
    firstFlight: 1975,
    crew: 1,
    engineCount: 2,
    engine: 'Soyuz R-95',
    horsepower: null,
    topSpeed: 606,
    range: 465,
    wingspan: 47,
    serviceCeiling: 23000
  },

  {
    name: 'blackbird',
    id: 55,
    designation: 'sr-71',
    fullName: 'SR-71 Blackbird',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Reconnaissance',
    role: 'Strategic Recon',
    firstFlight: 1964,
    crew: 2,
    engineCount: 2,
    engine: 'Pratt & Whitney J58',
    horsepower: null,
    topSpeed: 2193,
    range: 3200,
    wingspan: 55.5,
    serviceCeiling: 85000
  },

  {
    name: 'dragonLady',
    id: 56,
    designation: 'u-2',
    fullName: 'U-2 Dragon Lady',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Reconnaissance',
    role: 'High Altitude Recon',
    firstFlight: 1955,
    crew: 1,
    engineCount: 1,
    engine: 'General Electric F118',
    horsepower: null,
    topSpeed: 500,
    range: 6900,
    wingspan: 104,
    serviceCeiling: 70000
  },

  {
    name: 'raptor',
    id: 57,
    designation: 'f-22',
    fullName: 'F-22 Raptor',
    manufacturer: 'Lockheed Martin',
    country: 'USA',
    type: 'Stealth Fighter',
    role: 'Air Superiority',
    firstFlight: 1997,
    crew: 1,
    engineCount: 2,
    engine: 'Pratt & Whitney F119',
    horsepower: null,
    topSpeed: 1500,
    range: 1840,
    wingspan: 44.5,
    serviceCeiling: 65000
  },

  {
    name: 'lightningII',
    id: 58,
    designation: 'f-35',
    fullName: 'F-35 Lightning II',
    manufacturer: 'Lockheed Martin',
    country: 'USA',
    type: 'Stealth Fighter',
    role: 'Multirole',
    firstFlight: 2006,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney F135',
    horsepower: null,
    topSpeed: 1200,
    range: 1380,
    wingspan: 35,
    serviceCeiling: 50000
  },

  {
    name: 'su57',
    id: 59,
    designation: 'su-57',
    fullName: 'Sukhoi Su-57',
    manufacturer: 'Sukhoi',
    country: 'Russia',
    type: 'Stealth Fighter',
    role: 'Multirole',
    firstFlight: 2010,
    crew: 1,
    engineCount: 2,
    engine: 'Saturn AL-41F1',
    horsepower: null,
    topSpeed: 1600,
    range: 2175,
    wingspan: 46,
    serviceCeiling: 65000
  },

  {
    name: 'rafale',
    id: 60,
    designation: 'rafale',
    fullName: 'Dassault Rafale',
    manufacturer: 'Dassault Aviation',
    country: 'France',
    type: 'Fighter',
    role: 'Multirole',
    firstFlight: 1986,
    crew: 1,
    engineCount: 2,
    engine: 'Snecma M88',
    horsepower: null,
    topSpeed: 1190,
    range: 2300,
    wingspan: 35.9,
    serviceCeiling: 50000
  },

  {
    name: 'typhoon',
    id: 61,
    designation: 'ef-2000',
    fullName: 'Eurofighter Typhoon',
    manufacturer: 'Eurofighter GmbH',
    country: 'Europe',
    type: 'Fighter',
    role: 'Multirole',
    firstFlight: 1994,
    crew: 1,
    engineCount: 2,
    engine: 'Eurojet EJ200',
    horsepower: null,
    topSpeed: 1550,
    range: 1800,
    wingspan: 35.9,
    serviceCeiling: 65000
  },

  {
    name: 'gripen',
    id: 62,
    designation: 'jas-39',
    fullName: 'JAS 39 Gripen',
    manufacturer: 'Saab',
    country: 'Sweden',
    type: 'Fighter',
    role: 'Multirole',
    firstFlight: 1988,
    crew: 1,
    engineCount: 1,
    engine: 'Volvo RM12',
    horsepower: null,
    topSpeed: 1370,
    range: 2000,
    wingspan: 27.6,
    serviceCeiling: 50000
  },

  {
    name: 'j20',
    id: 63,
    designation: 'j-20',
    fullName: 'Chengdu J-20 Mighty Dragon',
    manufacturer: 'Chengdu Aerospace Corporation',
    country: 'China',
    type: 'Stealth Fighter',
    role: 'Air Superiority',
    firstFlight: 2011,
    crew: 1,
    engineCount: 2,
    engine: 'WS-10C',
    horsepower: null,
    topSpeed: 1300,
    range: 3400,
    wingspan: 43,
    serviceCeiling: 66000
  },

  {
    name: 'kf21',
    id: 64,
    designation: 'kf-21',
    fullName: 'KF-21 Boramae',
    manufacturer: 'KAI',
    country: 'South Korea',
    type: 'Fighter',
    role: 'Multirole',
    firstFlight: 2022,
    crew: 1,
    engineCount: 2,
    engine: 'General Electric F414',
    horsepower: null,
    topSpeed: 1370,
    range: 1800,
    wingspan: 38,
    serviceCeiling: 55000
  },

  {
    name: 'tejas',
    id: 65,
    designation: 'tejas',
    fullName: 'HAL Tejas',
    manufacturer: 'Hindustan Aeronautics Limited',
    country: 'India',
    type: 'Fighter',
    role: 'Multirole',
    firstFlight: 2001,
    crew: 1,
    engineCount: 1,
    engine: 'General Electric F404',
    horsepower: null,
    topSpeed: 1376,
    range: 1050,
    wingspan: 26.9,
    serviceCeiling: 52000
  },

  {
    name: 'superTucano',
    id: 66,
    designation: 'a-29',
    fullName: 'Embraer A-29 Super Tucano',
    manufacturer: 'Embraer',
    country: 'Brazil',
    type: 'Turboprop Attack Aircraft',
    role: 'Light Attack / Trainer',
    firstFlight: 1999,
    crew: 2,
    engineCount: 1,
    engine: 'Pratt & Whitney PT6A-68C',
    horsepower: 1600,
    topSpeed: 367,
    range: 830,
    wingspan: 36.5,
    serviceCeiling: 35000
  },

  {
    name: 'skyradesignationerII',
    id: 67,
    designation: 'oa-1',
    variant: 'K',
    fullName: 'OA-1K Skyradesignationer II',
    manufacturer: 'L3Harris / Air Tractor',
    country: 'USA',
    type: 'Turboprop Attack Aircraft',
    role: 'Armed Overwatch',
    firstFlight: 2022,
    crew: 2,
    engineCount: 1,
    engine: 'Pratt & Whitney PT6A',
    horsepower: 1600,
    topSpeed: 245,
    range: 1300,
    wingspan: 59,
    serviceCeiling: 35000
  },

  {
    name: 'bronco',
    id: 68,
    designation: 'ov-10',
    fullName: 'OV-10 Bronco',
    manufacturer: 'North American Rockwell',
    country: 'USA',
    type: 'Light Attack Aircraft',
    role: 'Forward Air Control',
    firstFlight: 1965,
    crew: 2,
    engineCount: 2,
    engine: 'Garrett T76',
    horsepower: 715,
    topSpeed: 281,
    range: 1380,
    wingspan: 40,
    serviceCeiling: 26000
  },

  {
    name: 'warden',
    id: 69,
    designation: 'mc-208',
    fullName: 'MC-208 Guardian',
    manufacturer: 'Cessna',
    country: 'USA',
    type: 'ISR Aircraft',
    role: 'Surveillance / Light Attack',
    firstFlight: 1982,
    crew: 2,
    engineCount: 1,
    engine: 'Pratt & Whitney PT6A',
    horsepower: 867,
    topSpeed: 214,
    range: 1200,
    wingspan: 52.1,
    serviceCeiling: 31000
  },

  {
    name: 'hellcat',
    id: 70,
    designation: 'f6f',
    variant: '5',
    fullName: 'F6F Hellcat',
    manufacturer: 'Grumman',
    country: 'USA',
    type: 'Carrier Fighter',
    role: 'Multirole',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney R-2800',
    horsepower: 2000,
    topSpeed: 391,
    range: 945,
    wingspan: 42.8,
    serviceCeiling: 37300
  },

  {
    name: 'warhawk',
    id: 71,
    designation: 'p-40',
    fullName: 'P-40 Warhawk',
    manufacturer: 'Curtiss',
    country: 'USA',
    type: 'Fighter',
    role: 'Fighter Bomber',
    firstFlight: 1938,
    crew: 1,
    engineCount: 1,
    engine: 'Allison V-1710',
    horsepower: 1150,
    topSpeed: 360,
    range: 716,
    wingspan: 37.3,
    serviceCeiling: 29000
  },

  {
    name: 'liberator',
    id: 72,
    designation: 'b-24',
    fullName: 'B-24 Liberator',
    manufacturer: 'Consoldesignationated',
    country: 'USA',
    type: 'Bomber',
    role: 'Heavy Bomber',
    firstFlight: 1939,
    crew: 11,
    engineCount: 4,
    engine: 'Pratt & Whitney R-1830',
    horsepower: 1200,
    topSpeed: 290,
    range: 2100,
    wingspan: 110,
    serviceCeiling: 28000
  },

  {
    name: 'mitchell',
    id: 73,
    designation: 'b-25',
    fullName: 'B-25 Mitchell',
    manufacturer: 'North American Aviation',
    country: 'USA',
    type: 'Bomber',
    role: 'Medium Bomber',
    firstFlight: 1940,
    crew: 6,
    engineCount: 2,
    engine: 'Wright R-2600',
    horsepower: 1700,
    topSpeed: 272,
    range: 1350,
    wingspan: 67.6,
    serviceCeiling: 24200
  },

  {
    name: 'stuka',
    id: 74,
    designation: 'ju-87',
    fullName: 'Junkers Ju 87 Stuka',
    manufacturer: 'Junkers',
    country: 'Germany',
    type: 'Bomber',
    role: 'Dive Bomber',
    firstFlight: 1935,
    crew: 2,
    engineCount: 1,
    engine: 'Junkers Jumo 211',
    horsepower: 1184,
    topSpeed: 242,
    range: 311,
    wingspan: 45.3,
    serviceCeiling: 26900
  },

  {
    name: 'stratofortress',
    id: 75,
    designation: 'b-52',
    fullName: 'B-52 Stratofortress',
    manufacturer: 'Boeing',
    country: 'USA',
    type: 'Bomber',
    role: 'Strategic Bomber',
    firstFlight: 1952,
    crew: 5,
    engineCount: 8,
    engine: 'Pratt & Whitney TF33',
    horsepower: null,
    topSpeed: 650,
    range: 8800,
    wingspan: 185,
    serviceCeiling: 50000
  },

  {
    name: 'spirit',
    id: 76,
    designation: 'b-2',
    fullName: 'B-2 Spirit',
    manufacturer: 'Northrop Grumman',
    country: 'USA',
    type: 'Stealth Bomber',
    role: 'Strategic Bomber',
    firstFlight: 1989,
    crew: 2,
    engineCount: 4,
    engine: 'General Electric F118',
    horsepower: null,
    topSpeed: 630,
    range: 6900,
    wingspan: 172,
    serviceCeiling: 50000
  },

  {
    name: 'lancer',
    id: 77,
    designation: 'b-1',
    variant: 'B',
    fullName: 'B-1B Lancer',
    manufacturer: 'Rockwell',
    country: 'USA',
    type: 'Bomber',
    role: 'Strategic Bomber',
    firstFlight: 1974,
    crew: 4,
    engineCount: 4,
    engine: 'General Electric F101',
    horsepower: null,
    topSpeed: 830,
    range: 5900,
    wingspan: 137,
    serviceCeiling: 60000
  },

  {
    name: 'nighthawk',
    id: 78,
    designation: 'f-117',
    fullName: 'F-117 Nighthawk',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Stealth Attack',
    role: 'Ground Attack',
    firstFlight: 1981,
    crew: 1,
    engineCount: 2,
    engine: 'General Electric F404',
    horsepower: null,
    topSpeed: 619,
    range: 1070,
    wingspan: 43.3,
    serviceCeiling: 45000
  },

  {
    name: 'foxbat',
    id: 79,
    designation: 'mig-25',
    fullName: 'MiG-25',
    manufacturer: 'Mikoyan-Gurevich',
    country: 'USSR',
    type: 'Interceptor',
    role: 'High Speed Interceptor',
    firstFlight: 1964,
    crew: 1,
    engineCount: 2,
    engine: 'Tumansky R-15',
    horsepower: null,
    topSpeed: 1900,
    range: 1075,
    wingspan: 46,
    serviceCeiling: 67900
  },

  {
    name: 'mirage2000',
    id: 80,
    designation: 'mirage-2000',
    fullName: 'Mirage 2000',
    manufacturer: 'Dassault Aviation',
    country: 'France',
    type: 'Fighter',
    role: 'Multirole',
    firstFlight: 1978,
    crew: 1,
    engineCount: 1,
    engine: 'Snecma M53',
    horsepower: null,
    topSpeed: 1453,
    range: 963,
    wingspan: 29.9,
    serviceCeiling: 55770
  },

  {
    name: 'tornado',
    id: 81,
    designation: 'tornado',
    fullName: 'Panavia Tornado',
    manufacturer: 'Panavia Aircraft',
    country: 'Europe',
    type: 'Strike Aircraft',
    role: 'Multirole',
    firstFlight: 1974,
    crew: 2,
    engineCount: 2,
    engine: 'Turbo-Union RB199',
    horsepower: null,
    topSpeed: 1490,
    range: 870,
    wingspan: 45.6,
    serviceCeiling: 50000
  },

  {
    name: 'skyhawk',
    id: 82,
    designation: 'a-4',
    fullName: 'A-4 Skyhawk',
    manufacturer: 'Douglas',
    country: 'USA',
    type: 'Attack',
    role: 'Light Attack',
    firstFlight: 1954,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney J52',
    horsepower: null,
    topSpeed: 670,
    range: 2000,
    wingspan: 27.5,
    serviceCeiling: 42250
  },

  {
    name: 'intruder',
    id: 83,
    designation: 'a-6',
    fullName: 'A-6 Intruder',
    manufacturer: 'Grumman',
    country: 'USA',
    type: 'Attack',
    role: 'All-Weather Attack',
    firstFlight: 1960,
    crew: 2,
    engineCount: 2,
    engine: 'Pratt & Whitney J52',
    horsepower: null,
    topSpeed: 644,
    range: 3245,
    wingspan: 53,
    serviceCeiling: 40600
  },

  {
    name: 'hercules',
    id: 84,
    designation: 'c-130',
    fullName: 'C-130 Hercules',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Transport',
    role: 'Tactical Airlift',
    firstFlight: 1954,
    crew: 5,
    engineCount: 4,
    engine: 'Allison T56',
    horsepower: 4590,
    topSpeed: 366,
    range: 2360,
    wingspan: 132.6,
    serviceCeiling: 33000
  },

  {
    name: 'crusader',
    id: 85,
    designation: 'f-8',
    fullName: 'F-8 Crusader',
    manufacturer: 'Vought',
    country: 'USA',
    type: 'Carrier Fighter',
    role: 'Air Superiority',
    firstFlight: 1955,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney J57',
    horsepower: null,
    topSpeed: 1225,
    range: 1735,
    wingspan: 35.2,
    serviceCeiling: 58000
  },

  {
    name: 'fullback',
    id: 86,
    designation: 'su-34',
    fullName: 'Su-34',
    manufacturer: 'Sukhoi',
    country: 'Russia',
    type: 'Strike Fighter',
    role: 'Fighter Bomber',
    firstFlight: 1990,
    crew: 2,
    engineCount: 2,
    engine: 'Saturn AL-31FM1',
    horsepower: null,
    topSpeed: 1180,
    range: 2485,
    wingspan: 48.3,
    serviceCeiling: 55800
  },

  {
    name: 'vigorousDragon',
    id: 87,
    designation: 'j-10',
    fullName: 'Chengdu J-10',
    manufacturer: 'Chengdu Aerospace Corporation',
    country: 'China',
    type: 'Fighter',
    role: 'Multirole',
    firstFlight: 1998,
    crew: 1,
    engineCount: 1,
    engine: 'Saturn AL-31FN',
    horsepower: null,
    topSpeed: 1450,
    range: 1988,
    wingspan: 32,
    serviceCeiling: 59000
  },

  {
    name: 'harrier',
    id: 88,
    designation: 'av-8',
    variant: 'B',
    fullName: 'AV-8B Harrier II',
    manufacturer: 'McDonnell Douglas',
    country: 'USA',
    type: 'Attack',
    role: 'V/STOL Attack',
    firstFlight: 1978,
    crew: 1,
    engineCount: 1,
    engine: 'Rolls-Royce Pegasus F402',
    horsepower: null,
    topSpeed: 662,
    range: 1400,
    wingspan: 30.3,
    serviceCeiling: 35000
  },

  {
    name: 'tigerII',
    id: 89,
    designation: 'f-5',
    fullName: 'F-5 Tiger II',
    manufacturer: 'Northrop',
    country: 'USA',
    type: 'Fighter',
    role: 'Light Fighter',
    firstFlight: 1959,
    crew: 1,
    engineCount: 2,
    engine: 'General Electric J85',
    horsepower: null,
    topSpeed: 1060,
    range: 870,
    wingspan: 26.7,
    serviceCeiling: 51800
  },

  {
    name: 'dauntless',
    id: 90,
    designation: 'sbd',
    fullName: 'SBD Dauntless',
    manufacturer: 'Douglas',
    country: 'USA',
    type: 'Bomber',
    role: 'Dive Bomber',
    firstFlight: 1940,
    crew: 2,
    engineCount: 1,
    engine: 'Wright R-1820',
    horsepower: 1200,
    topSpeed: 255,
    range: 1115,
    wingspan: 41.5,
    serviceCeiling: 25500
  },

  {
    name: 'avenger',
    id: 91,
    designation: 'tbf',
    fullName: 'TBF Avenger',
    manufacturer: 'Grumman',
    country: 'USA',
    type: 'Bomber',
    role: 'Torpedo Bomber',
    firstFlight: 1941,
    crew: 3,
    engineCount: 1,
    engine: 'Wright R-2600',
    horsepower: 1900,
    topSpeed: 275,
    range: 1000,
    wingspan: 54.2,
    serviceCeiling: 30100
  },

  {
    name: 'wildcat',
    id: 92,
    designation: 'f4f',
    fullName: 'F4F Wildcat',
    manufacturer: 'Grumman',
    country: 'USA',
    type: 'Carrier Fighter',
    role: 'Fighter',
    firstFlight: 1937,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney R-1830',
    horsepower: 1200,
    topSpeed: 331,
    range: 845,
    wingspan: 38,
    serviceCeiling: 39500
  },

  {
    name: 'thunderchief',
    id: 93,
    designation: 'f-105',
    fullName: 'F-105 Thunderchief',
    manufacturer: 'Republic Aviation',
    country: 'USA',
    type: 'Fighter Bomber',
    role: 'Strike',
    firstFlight: 1955,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney J75',
    horsepower: null,
    topSpeed: 1372,
    range: 2200,
    wingspan: 34.9,
    serviceCeiling: 48500
  },

  {
    name: 'strikeEagle',
    id: 94,
    designation: 'f-15',
    variant: 'E',
    fullName: 'F-15E Strike Eagle',
    manufacturer: 'McDonnell Douglas',
    country: 'USA',
    type: 'Strike Fighter',
    role: 'Multirole',
    firstFlight: 1986,
    crew: 2,
    engineCount: 2,
    engine: 'Pratt & Whitney F100',
    horsepower: null,
    topSpeed: 1650,
    range: 2400,
    wingspan: 42.8,
    serviceCeiling: 60000
  },

  {
    name: 'blackWdesignationow',
    id: 95,
    designation: 'p-61',
    fullName: 'P-61 Black Wdesignationow',
    manufacturer: 'Northrop',
    country: 'USA',
    type: 'Heavy Fighter',
    role: 'Night Fighter',
    firstFlight: 1942,
    crew: 3,
    engineCount: 2,
    engine: 'Pratt & Whitney R-2800',
    horsepower: 2250,
    topSpeed: 366,
    range: 1900,
    wingspan: 66,
    serviceCeiling: 33100
  },

  {
    name: 'skytrain',
    id: 96,
    designation: 'c-47',
    fullName: 'C-47 Skytrain',
    manufacturer: 'Douglas',
    country: 'USA',
    type: 'Transport',
    role: 'Tactical Airlift',
    firstFlight: 1941,
    crew: 4,
    engineCount: 2,
    engine: 'Pratt & Whitney R-1830',
    horsepower: 1200,
    topSpeed: 224,
    range: 1600,
    wingspan: 95,
    serviceCeiling: 26400
  },

  {
    name: 'corsairII',
    id: 97,
    designation: 'a-7',
    fullName: 'A-7 Corsair II',
    manufacturer: 'LTV',
    country: 'USA',
    type: 'Attack',
    role: 'Light Attack',
    firstFlight: 1965,
    crew: 1,
    engineCount: 1,
    engine: 'Allison TF41',
    horsepower: null,
    topSpeed: 690,
    range: 1170,
    wingspan: 38.7,
    serviceCeiling: 42000
  },

  {
    name: 'lightningUK',
    id: 98,
    designation: 'bac-lightning',
    fullName: 'English Electric Lightning',
    manufacturer: 'English Electric',
    country: 'UK',
    type: 'Interceptor',
    role: 'Point Defense',
    firstFlight: 1954,
    crew: 1,
    engineCount: 2,
    engine: 'Rolls-Royce Avon',
    horsepower: null,
    topSpeed: 1500,
    range: 850,
    wingspan: 34.8,
    serviceCeiling: 54000
  },

  {
    name: 'mirageIII',
    id: 99,
    designation: 'mirage',
    variant: 'III',
    fullName: 'Mirage III',
    manufacturer: 'Dassault Aviation',
    country: 'France',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1956,
    crew: 1,
    engineCount: 1,
    engine: 'Snecma Atar 09C',
    horsepower: null,
    topSpeed: 1460,
    range: 1000,
    wingspan: 27,
    serviceCeiling: 55700
  },

  {
    name: 'bear',
    id: 100,
    designation: 'tu-95',
    fullName: 'Tu-95 Bear',
    manufacturer: 'Tupolev',
    country: 'USSR',
    type: 'Bomber',
    role: 'Strategic Bomber',
    firstFlight: 1952,
    crew: 6,
    engineCount: 4,
    engine: 'Kuznetsov NK-12',
    horsepower: 15000,
    topSpeed: 575,
    range: 9320,
    wingspan: 164,
    serviceCeiling: 45000
  },

  {
    name: 'foxhound',
    id: 101,
    designation: 'mig-31',
    fullName: 'MiG-31 Foxhound',
    manufacturer: 'Mikoyan',
    country: 'USSR',
    type: 'Interceptor',
    role: 'High Speed Interceptor',
    firstFlight: 1975,
    crew: 2,
    engineCount: 2,
    engine: 'Soloviev D-30F6',
    horsepower: null,
    topSpeed: 1860,
    range: 1860,
    wingspan: 44.2,
    serviceCeiling: 80000
  },

  {
    name: 'hustler',
    id: 102,
    designation: 'b-58',
    fullName: 'B-58 Hustler',
    manufacturer: 'Convair',
    country: 'USA',
    type: 'Bomber',
    role: 'Supersonic Bomber',
    firstFlight: 1956,
    crew: 3,
    engineCount: 4,
    engine: 'General Electric J79',
    horsepower: null,
    topSpeed: 1319,
    range: 4100,
    wingspan: 56.8,
    serviceCeiling: 63400
  },

  {
    name: 'deltaDart',
    id: 103,
    designation: 'f-106',
    fullName: 'F-106 Delta Dart',
    manufacturer: 'Convair',
    country: 'USA',
    type: 'Interceptor',
    role: 'All-Weather Interceptor',
    firstFlight: 1956,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney J75',
    horsepower: null,
    topSpeed: 1525,
    range: 1800,
    wingspan: 38.2,
    serviceCeiling: 57000
  },

  {
    name: 'fencer',
    id: 104,
    designation: 'su-24',
    fullName: 'Su-24 Fencer',
    manufacturer: 'Sukhoi',
    country: 'USSR',
    type: 'Strike Fighter',
    role: 'Interdiction',
    firstFlight: 1967,
    crew: 2,
    engineCount: 2,
    engine: 'Lyulka AL-21F-3A',
    horsepower: null,
    topSpeed: 1020,
    range: 1720,
    wingspan: 57.1,
    serviceCeiling: 36000
  },

  {
    name: 'viggen',
    id: 105,
    designation: 'ja-37',
    fullName: 'Saab 37 Viggen',
    manufacturer: 'Saab',
    country: 'Sweden',
    type: 'Fighter',
    role: 'Multirole',
    firstFlight: 1967,
    crew: 1,
    engineCount: 1,
    engine: 'Volvo RM8',
    horsepower: null,
    topSpeed: 1320,
    range: 1240,
    wingspan: 34.8,
    serviceCeiling: 59000
  },

  {
    name: 'draken',
    id: 106,
    designation: 'j-35',
    fullName: 'Saab 35 Draken',
    manufacturer: 'Saab',
    country: 'Sweden',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1955,
    crew: 1,
    engineCount: 1,
    engine: 'Volvo RM6C',
    horsepower: null,
    topSpeed: 1317,
    range: 1760,
    wingspan: 30.8,
    serviceCeiling: 65600
  },

  {
    name: 'vulcan',
    id: 107,
    designation: 'vulcan',
    variant: 'B2',
    fullName: 'Avro Vulcan',
    manufacturer: 'Avro',
    country: 'UK',
    type: 'Bomber',
    role: 'Strategic Bomber',
    firstFlight: 1952,
    crew: 5,
    engineCount: 4,
    engine: 'Rolls-Royce Olympus',
    horsepower: null,
    topSpeed: 646,
    range: 2600,
    wingspan: 111,
    serviceCeiling: 55000
  },

  {
    name: 'meteor',
    id: 108,
    designation: 'meteor',
    variant: 'F8',
    fullName: 'Gloster Meteor',
    manufacturer: 'Gloster',
    country: 'UK',
    type: 'Jet Fighter',
    role: 'Fighter',
    firstFlight: 1943,
    crew: 1,
    engineCount: 2,
    engine: 'Rolls-Royce Derwent',
    horsepower: null,
    topSpeed: 600,
    range: 600,
    wingspan: 43,
    serviceCeiling: 43000
  },

  {
    name: 'komet',
    id: 109,
    designation: 'me-163',
    fullName: 'Me 163 Komet',
    manufacturer: 'Messerschmitt',
    country: 'Germany',
    type: 'Rocket Fighter',
    role: 'Point Defense Interceptor',
    firstFlight: 1941,
    crew: 1,
    engineCount: 1,
    engine: 'Walter HWK 109-509',
    horsepower: null,
    topSpeed: 596,
    range: 25,
    wingspan: 30.6,
    serviceCeiling: 39000
  },

  {
    name: 'marauder',
    id: 110,
    designation: 'b-26',
    fullName: 'B-26 Marauder',
    manufacturer: 'Martin',
    country: 'USA',
    type: 'Bomber',
    role: 'Medium Bomber',
    firstFlight: 1940,
    crew: 7,
    engineCount: 2,
    engine: 'Pratt & Whitney R-2800',
    horsepower: 1920,
    topSpeed: 287,
    range: 1150,
    wingspan: 71,
    serviceCeiling: 21000
  },

  {
    name: 'hayate',
    id: 111,
    designation: 'ki-84',
    fullName: 'Nakajima Ki-84 Hayate',
    manufacturer: 'Nakajima',
    country: 'Japan',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1943,
    crew: 1,
    engineCount: 1,
    engine: 'Nakajima Ha-45',
    horsepower: 1900,
    topSpeed: 427,
    range: 1335,
    wingspan: 36.9,
    serviceCeiling: 34450
  },

  {
    name: 'voodoo',
    id: 112,
    designation: 'f-101',
    fullName: 'F-101 Voodoo',
    manufacturer: 'McDonnell',
    country: 'USA',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1954,
    crew: 2,
    engineCount: 2,
    engine: 'Pratt & Whitney J57',
    horsepower: null,
    topSpeed: 1134,
    range: 1520,
    wingspan: 39.7,
    serviceCeiling: 58400
  },

  {
    name: 'thunderjet',
    id: 113,
    designation: 'f-84',
    fullName: 'F-84 Thunderjet',
    manufacturer: 'Republic Aviation',
    country: 'USA',
    type: 'Jet Fighter',
    role: 'Fighter Bomber',
    firstFlight: 1946,
    crew: 1,
    engineCount: 1,
    engine: 'Allison J35',
    horsepower: null,
    topSpeed: 622,
    range: 1000,
    wingspan: 36.4,
    serviceCeiling: 40500
  },

  {
    name: 'superHornet',
    id: 114,
    designation: 'fa-18',
    variant: 'E',
    fullName: 'F/A-18E Super Hornet',
    manufacturer: 'Boeing',
    country: 'USA',
    type: 'Carrier Fighter',
    role: 'Multirole',
    firstFlight: 1995,
    crew: 1,
    engineCount: 2,
    engine: 'General Electric F414',
    horsepower: null,
    topSpeed: 1190,
    range: 1275,
    wingspan: 44.7,
    serviceCeiling: 50000
  },

  {
    name: 'flankerE',
    id: 115,
    designation: 'su-35',
    fullName: 'Su-35S',
    manufacturer: 'Sukhoi',
    country: 'Russia',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 2008,
    crew: 1,
    engineCount: 2,
    engine: 'Saturn AL-41F1S',
    horsepower: null,
    topSpeed: 1490,
    range: 2235,
    wingspan: 50.2,
    serviceCeiling: 59000
  },

  {
    name: 'hdesignationdenDragon',
    id: 116,
    designation: 'j-16',
    fullName: 'Shenyang J-16',
    manufacturer: 'Shenyang Aircraft Corporation',
    country: 'China',
    type: 'Strike Fighter',
    role: 'Multirole',
    firstFlight: 2012,
    crew: 2,
    engineCount: 2,
    engine: 'Shenyang WS-10B',
    horsepower: null,
    topSpeed: 1490,
    range: 1864,
    wingspan: 48.3,
    serviceCeiling: 56800
  },

  {
    name: 'swordfish',
    id: 117,
    designation: 'swordfish',
    fullName: 'Fairey Swordfish',
    manufacturer: 'Fairey',
    country: 'UK',
    type: 'Biplane Bomber',
    role: 'Torpedo Bomber',
    firstFlight: 1934,
    crew: 3,
    engineCount: 1,
    engine: 'Bristol Pegasus',
    horsepower: 690,
    topSpeed: 143,
    range: 522,
    wingspan: 45.5,
    serviceCeiling: 16500
  },

  {
    name: 'havoc',
    id: 118,
    designation: 'a-20',
    fullName: 'A-20 Havoc',
    manufacturer: 'Douglas',
    country: 'USA',
    type: 'Bomber',
    role: 'Light Bomber',
    firstFlight: 1939,
    crew: 3,
    engineCount: 2,
    engine: 'Wright R-2600',
    horsepower: 1600,
    topSpeed: 317,
    range: 945,
    wingspan: 61.3,
    serviceCeiling: 23700
  },

  {
    name: 'catalina',
    id: 119,
    designation: 'pby',
    fullName: 'PBY Catalina',
    manufacturer: 'Consoldesignationated',
    country: 'USA',
    type: 'Flying Boat',
    role: 'Patrol Bomber',
    firstFlight: 1935,
    crew: 10,
    engineCount: 2,
    engine: 'Pratt & Whitney R-1830',
    horsepower: 1200,
    topSpeed: 196,
    range: 2520,
    wingspan: 104,
    serviceCeiling: 15800
  },

  {
    name: 'osprey',
    id: 120,
    designation: 'v-22',
    fullName: 'V-22 Osprey',
    manufacturer: 'Bell Boeing',
    country: 'USA',
    type: 'Tiltrotor',
    role: 'Transport',
    firstFlight: 1989,
    crew: 4,
    engineCount: 2,
    engine: 'Rolls-Royce T406',
    horsepower: 6150,
    topSpeed: 316,
    range: 1011,
    wingspan: 45.8,
    serviceCeiling: 25000
  },

  {
    name: 'spooky',
    id: 121,
    designation: 'ac-130',
    fullName: 'AC-130 Spooky',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Gunship',
    role: 'Close Air Support',
    firstFlight: 1966,
    crew: 13,
    engineCount: 4,
    engine: 'Allison T56',
    horsepower: 4910,
    topSpeed: 300,
    range: 2530,
    wingspan: 132.6,
    serviceCeiling: 30000
  },

  {
    name: 'fresco',
    id: 122,
    designation: 'mig-17',
    fullName: 'MiG-17',
    manufacturer: 'Mikoyan-Gurevich',
    country: 'USSR',
    type: 'Jet Fighter',
    role: 'Interceptor',
    firstFlight: 1950,
    crew: 1,
    engineCount: 1,
    engine: 'Klimov VK-1F',
    horsepower: null,
    topSpeed: 711,
    range: 1255,
    wingspan: 31.6,
    serviceCeiling: 54500
  },

  {
    name: 'globemasterIII',
    id: 123,
    designation: 'c-17',
    fullName: 'C-17 Globemaster III',
    manufacturer: 'Boeing',
    country: 'USA',
    type: 'Transport',
    role: 'Strategic Airlift',
    firstFlight: 1991,
    crew: 3,
    engineCount: 4,
    engine: 'Pratt & Whitney F117',
    horsepower: null,
    topSpeed: 520,
    range: 2780,
    wingspan: 169.8,
    serviceCeiling: 45000
  },

  {
    name: 'growler',
    id: 124,
    designation: 'ea-18',
    variant: 'G',
    fullName: 'EA-18G Growler',
    manufacturer: 'Boeing',
    country: 'USA',
    type: 'Electronic Warfare',
    role: 'Electronic Attack',
    firstFlight: 2006,
    crew: 2,
    engineCount: 2,
    engine: 'General Electric F414',
    horsepower: null,
    topSpeed: 1190,
    range: 1275,
    wingspan: 44.7,
    serviceCeiling: 50000
  },

  {
    name: 'airacobra',
    id: 125,
    designation: 'p-39',
    fullName: 'P-39 Airacobra',
    manufacturer: 'Bell Aircraft',
    country: 'USA',
    type: 'Fighter',
    role: 'Ground Attack / Interceptor',
    firstFlight: 1938,
    crew: 1,
    engineCount: 1,
    engine: 'Allison V-1710',
    horsepower: 1200,
    topSpeed: 389,
    range: 525,
    wingspan: 34,
    serviceCeiling: 35000
  },

  {
    name: 'galaxy',
    id: 126,
    designation: 'c-5',
    fullName: 'C-5 Galaxy',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Transport',
    role: 'Strategic Airlift',
    firstFlight: 1968,
    crew: 7,
    engineCount: 4,
    engine: 'General Electric TF39',
    horsepower: null,
    topSpeed: 532,
    range: 4800,
    wingspan: 222.9,
    serviceCeiling: 35700
  },

  {
    name: 'peacemaker',
    id: 127,
    designation: 'b-36',
    fullName: 'B-36 Peacemaker',
    manufacturer: 'Convair',
    country: 'USA',
    type: 'Bomber',
    role: 'Strategic Bomber',
    firstFlight: 1946,
    crew: 13,
    engineCount: 10,
    engine: 'Pratt & Whitney R-4360 / General Electric J47',
    horsepower: 3800,
    topSpeed: 436,
    range: 10000,
    wingspan: 230,
    serviceCeiling: 43600
  },

  {
    name: 'shootingStar',
    id: 128,
    designation: 'f-80',
    fullName: 'F-80 Shooting Star',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Jet Fighter',
    role: 'Fighter Bomber',
    firstFlight: 1944,
    crew: 1,
    engineCount: 1,
    engine: 'Allison J33',
    horsepower: null,
    topSpeed: 594,
    range: 1090,
    wingspan: 38.9,
    serviceCeiling: 46800
  },

  {
    name: 'panther',
    id: 129,
    designation: 'f9f',
    fullName: 'F9F Panther',
    manufacturer: 'Grumman',
    country: 'USA',
    type: 'Jet Fighter',
    role: 'Carrier Fighter',
    firstFlight: 1947,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney J42',
    horsepower: null,
    topSpeed: 575,
    range: 1300,
    wingspan: 38,
    serviceCeiling: 44600
  },

  {
    name: 'viking',
    id: 130,
    designation: 's-3',
    fullName: 'S-3 Viking',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Anti-Submarine',
    role: 'Carrier-based ASW',
    firstFlight: 1972,
    crew: 4,
    engineCount: 2,
    engine: 'General Electric TF34',
    horsepower: null,
    topSpeed: 493,
    range: 3182,
    wingspan: 68.7,
    serviceCeiling: 40900
  },

  {
    name: 'hawkeye',
    id: 131,
    designation: 'e-2',
    fullName: 'E-2 Hawkeye',
    manufacturer: 'Northrop Grumman',
    country: 'USA',
    type: 'AEW&C',
    role: 'Airborne Early Warning',
    firstFlight: 1960,
    crew: 5,
    engineCount: 2,
    engine: 'Rolls-Royce T56',
    horsepower: 5100,
    topSpeed: 350,
    range: 1462,
    wingspan: 80.6,
    serviceCeiling: 34700
  },

  {
    name: 'sentry',
    id: 132,
    designation: 'e-3',
    fullName: 'E-3 Sentry',
    manufacturer: 'Boeing',
    country: 'USA',
    type: 'AWACS',
    role: 'Airborne Warning and Control',
    firstFlight: 1975,
    crew: 20,
    engineCount: 4,
    engine: 'Pratt & Whitney TF33',
    horsepower: null,
    topSpeed: 530,
    range: 4000,
    wingspan: 145.8,
    serviceCeiling: 29000
  },

  {
    name: 'prowler',
    id: 133,
    designation: 'ea-6',
    variant: 'B',
    fullName: 'EA-6B Prowler',
    manufacturer: 'Grumman',
    country: 'USA',
    type: 'Electronic Warfare',
    role: 'Electronic Attack',
    firstFlight: 1968,
    crew: 4,
    engineCount: 2,
    engine: 'Pratt & Whitney J52',
    horsepower: null,
    topSpeed: 651,
    range: 2400,
    wingspan: 53,
    serviceCeiling: 37600
  },

  {
    name: 'stratojet',
    id: 134,
    designation: 'b-47',
    fullName: 'B-47 Stratojet',
    manufacturer: 'Boeing',
    country: 'USA',
    type: 'Bomber',
    role: 'Strategic Bomber',
    firstFlight: 1947,
    crew: 3,
    engineCount: 6,
    engine: 'General Electric J47',
    horsepower: null,
    topSpeed: 607,
    range: 3240,
    wingspan: 116,
    serviceCeiling: 33100
  },

  {
    name: 'farmer',
    id: 135,
    designation: 'mig-19',
    fullName: 'MiG-19',
    manufacturer: 'Mikoyan-Gurevich',
    country: 'USSR',
    type: 'Jet Fighter',
    role: 'Interceptor',
    firstFlight: 1953,
    crew: 1,
    engineCount: 2,
    engine: 'Tumansky RD-9B',
    horsepower: null,
    topSpeed: 902,
    range: 1367,
    wingspan: 29.5,
    serviceCeiling: 57400
  },

  {
    name: 'floggerD',
    id: 136,
    designation: 'mig-27',
    fullName: 'MiG-27',
    manufacturer: 'Mikoyan-Gurevich',
    country: 'USSR',
    type: 'Strike Fighter',
    role: 'Ground Attack',
    firstFlight: 1970,
    crew: 1,
    engineCount: 1,
    engine: 'Tumansky R-29B-300',
    horsepower: null,
    topSpeed: 1170,
    range: 1390,
    wingspan: 45.8,
    serviceCeiling: 45900
  },

  {
    name: 'fitter',
    id: 137,
    designation: 'su-17',
    fullName: 'Su-17',
    manufacturer: 'Sukhoi',
    country: 'USSR',
    type: 'Strike Fighter',
    role: 'Fighter Bomber',
    firstFlight: 1966,
    crew: 1,
    engineCount: 1,
    engine: 'Lyulka AL-21F-3',
    horsepower: null,
    topSpeed: 1155,
    range: 1240,
    wingspan: 45.3,
    serviceCeiling: 46590
  },

  {
    name: 'forger',
    id: 138,
    designation: 'yak-38',
    fullName: 'Yak-38',
    manufacturer: 'Yakovlev',
    country: 'USSR',
    type: 'VTOL Fighter',
    role: 'Fleet Defense',
    firstFlight: 1971,
    crew: 1,
    engineCount: 3,
    engine: 'Tumansky R-28 / Rybinsk RD-38',
    horsepower: null,
    topSpeed: 795,
    range: 800,
    wingspan: 23.9,
    serviceCeiling: 39370
  },

  {
    name: 'canberra',
    id: 139,
    designation: 'b-57',
    fullName: 'Martin B-57 Canberra',
    manufacturer: 'Martin',
    country: 'USA',
    type: 'Bomber',
    role: 'Tactical Bomber / Recon',
    firstFlight: 1953,
    crew: 2,
    engineCount: 2,
    engine: 'Wright J65',
    horsepower: null,
    topSpeed: 598,
    range: 2720,
    wingspan: 64,
    serviceCeiling: 45100
  },

  {
    name: 'tiger',
    id: 140,
    designation: 'f-11',
    fullName: 'F-11 Tiger',
    manufacturer: 'Grumman',
    country: 'USA',
    type: 'Carrier Fighter',
    role: 'Interceptor',
    firstFlight: 1954,
    crew: 1,
    engineCount: 1,
    engine: 'Wright J65',
    horsepower: null,
    topSpeed: 727,
    range: 1275,
    wingspan: 31.6,
    serviceCeiling: 49000
  },

  {
    name: 'scorpion',
    id: 141,
    designation: 'f-89',
    fullName: 'F-89 Scorpion',
    manufacturer: 'Northrop',
    country: 'USA',
    type: 'Interceptor',
    role: 'All-Weather Interceptor',
    firstFlight: 1948,
    crew: 2,
    engineCount: 2,
    engine: 'Allison J35',
    horsepower: null,
    topSpeed: 632,
    range: 1366,
    wingspan: 59.7,
    serviceCeiling: 49200
  },

  {
    name: 'dragonfly',
    id: 142,
    designation: 'a-37',
    fullName: 'A-37 Dragonfly',
    manufacturer: 'Cessna',
    country: 'USA',
    type: 'Light Attack',
    role: 'Close Air Support',
    firstFlight: 1963,
    crew: 2,
    engineCount: 2,
    engine: 'General Electric J85',
    horsepower: null,
    topSpeed: 507,
    range: 1012,
    wingspan: 35.8,
    serviceCeiling: 41765
  },

  {
    name: 'talon',
    id: 143,
    designation: 't-38',
    fullName: 'T-38 Talon',
    manufacturer: 'Northrop',
    country: 'USA',
    type: 'Trainer',
    role: 'Advanced Jet Trainer',
    firstFlight: 1959,
    crew: 2,
    engineCount: 2,
    engine: 'General Electric J85',
    horsepower: null,
    topSpeed: 858,
    range: 1140,
    wingspan: 25.2,
    serviceCeiling: 50000
  },

  {
    name: 'texan',
    id: 144,
    designation: 't-6',
    fullName: 'T-6 Texan',
    manufacturer: 'North American Aviation',
    country: 'USA',
    type: 'Trainer',
    role: 'Advanced Trainer',
    firstFlight: 1935,
    crew: 2,
    engineCount: 1,
    engine: 'Pratt & Whitney R-1340',
    horsepower: 600,
    topSpeed: 208,
    range: 730,
    wingspan: 42,
    serviceCeiling: 24200
  },

  {
    name: 'oscar',
    id: 145,
    designation: 'ki-43',
    fullName: 'Nakajima Ki-43 Hayabusa',
    manufacturer: 'Nakajima',
    country: 'Japan',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1939,
    crew: 1,
    engineCount: 1,
    engine: 'Nakajima Ha-115',
    horsepower: 1150,
    topSpeed: 330,
    range: 1990,
    wingspan: 35.6,
    serviceCeiling: 36750
  },

  {
    name: 'tony',
    id: 146,
    designation: 'ki-61',
    fullName: 'Kawasaki Ki-61 Hien',
    manufacturer: 'Kawasaki',
    country: 'Japan',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1941,
    crew: 1,
    engineCount: 1,
    engine: 'Kawasaki Ha-40',
    horsepower: 1159,
    topSpeed: 366,
    range: 1180,
    wingspan: 39.4,
    serviceCeiling: 38100
  },

  {
    name: 'betty',
    id: 147,
    designation: 'g4m',
    fullName: 'Mitsubishi G4M Betty',
    manufacturer: 'Mitsubishi',
    country: 'Japan',
    type: 'Bomber',
    role: 'Medium Bomber',
    firstFlight: 1939,
    crew: 7,
    engineCount: 2,
    engine: 'Mitsubishi Kasei',
    horsepower: 1530,
    topSpeed: 272,
    range: 3740,
    wingspan: 82,
    serviceCeiling: 29360
  },

  {
    name: 'val',
    id: 148,
    designation: 'd3a',
    fullName: 'Aichi D3A Val',
    manufacturer: 'Aichi',
    country: 'Japan',
    type: 'Bomber',
    role: 'Dive Bomber',
    firstFlight: 1938,
    crew: 2,
    engineCount: 1,
    engine: 'Mitsubishi Kinsei',
    horsepower: 1000,
    topSpeed: 240,
    range: 915,
    wingspan: 47.1,
    serviceCeiling: 32000
  },

  {
    name: 'kate',
    id: 149,
    designation: 'b5n',
    fullName: 'Nakajima B5N Kate',
    manufacturer: 'Nakajima',
    country: 'Japan',
    type: 'Bomber',
    role: 'Torpedo Bomber',
    firstFlight: 1937,
    crew: 3,
    engineCount: 1,
    engine: 'Nakajima Sakae',
    horsepower: 1000,
    topSpeed: 235,
    range: 1237,
    wingspan: 50.9,
    serviceCeiling: 27100
  },

  {
    name: 'panzerknacker',
    id: 150,
    designation: 'hs-129',
    fullName: 'Henschel Hs 129',
    manufacturer: 'Henschel',
    country: 'Germany',
    type: 'Attack',
    role: 'Ground Attack / Anti-Tank',
    firstFlight: 1939,
    crew: 1,
    engineCount: 2,
    engine: 'Gnome-Rhône 14M',
    horsepower: 700,
    topSpeed: 253,
    range: 428,
    wingspan: 46.7,
    serviceCeiling: 29500
  },

  {
    name: 'zerstorer',
    id: 151,
    designation: 'bf-110',
    fullName: 'Messerschmitt Bf 110',
    manufacturer: 'Messerschmitt',
    country: 'Germany',
    type: 'Heavy Fighter',
    role: 'Night Fighter / Zerstörer',
    firstFlight: 1936,
    crew: 2,
    engineCount: 2,
    engine: 'DB 601',
    horsepower: 1085,
    topSpeed: 349,
    range: 1500,
    wingspan: 53.4,
    serviceCeiling: 35000
  },

  {
    name: 'schnellbomber',
    id: 152,
    designation: 'ju-88',
    fullName: 'Junkers Ju 88',
    manufacturer: 'Junkers',
    country: 'Germany',
    type: 'Multirole',
    role: 'Bomber / Night Fighter',
    firstFlight: 1936,
    crew: 4,
    engineCount: 2,
    engine: 'Junkers Jumo 211',
    horsepower: 1184,
    topSpeed: 317,
    range: 1510,
    wingspan: 65.7,
    serviceCeiling: 29500
  },

  {
    name: 'he111',
    id: 153,
    designation: 'he-111',
    fullName: 'Heinkel He 111',
    manufacturer: 'Heinkel',
    country: 'Germany',
    type: 'Bomber',
    role: 'Medium Bomber',
    firstFlight: 1935,
    crew: 5,
    engineCount: 2,
    engine: 'Junkers Jumo 211',
    horsepower: 1300,
    topSpeed: 240,
    range: 1429,
    wingspan: 74.1,
    serviceCeiling: 21330
  },

  {
    name: 'wellington',
    id: 154,
    designation: 'wellington',
    fullName: 'Vickers Wellington',
    manufacturer: 'Vickers-Armstrongs',
    country: 'UK',
    type: 'Bomber',
    role: 'Medium Bomber',
    firstFlight: 1936,
    crew: 6,
    engineCount: 2,
    engine: 'Bristol Pegasus',
    horsepower: 1050,
    topSpeed: 235,
    range: 2550,
    wingspan: 86.2,
    serviceCeiling: 18000
  },

  {
    name: 'sopwithCamel',
    id: 155,
    designation: 'camel',
    fullName: 'Sopwith Camel',
    manufacturer: 'Sopwith Aviation Company',
    country: 'UK',
    type: 'Biplane Fighter',
    role: 'Fighter',
    firstFlight: 1917,
    crew: 1,
    engineCount: 1,
    engine: 'Clerget 9B Rotary',
    horsepower: 130,
    topSpeed: 113,
    range: 300,
    wingspan: 28,
    serviceCeiling: 19000
  },

  {
    name: 'fokkerDr1',
    id: 156,
    designation: 'dr-1',
    fullName: 'Fokker Dr.I',
    manufacturer: 'Fokker',
    country: 'Germany',
    type: 'Triplane Fighter',
    role: 'Fighter',
    firstFlight: 1917,
    crew: 1,
    engineCount: 1,
    engine: 'Oberursel UR.II Rotary',
    horsepower: 110,
    topSpeed: 115,
    range: 185,
    wingspan: 23.6,
    serviceCeiling: 20000
  },

  {
    name: 'spad13',
    id: 157,
    designation: 'spad',
    variant: 'XIII',
    fullName: 'SPAD S.XIII',
    manufacturer: 'Société Pour L\'Aviation et ses Dérivés',
    country: 'France',
    type: 'Biplane Fighter',
    role: 'Fighter',
    firstFlight: 1917,
    crew: 1,
    engineCount: 1,
    engine: 'Hispano-Suiza 8Be',
    horsepower: 220,
    topSpeed: 135,
    range: 171,
    wingspan: 26.6,
    serviceCeiling: 22300
  },

  {
    name: 'buffalo',
    id: 158,
    designation: 'f2a',
    fullName: 'F2A Buffalo',
    manufacturer: 'Brewster',
    country: 'USA',
    type: 'Carrier Fighter',
    role: 'Fighter',
    firstFlight: 1937,
    crew: 1,
    engineCount: 1,
    engine: 'Wright R-1820',
    horsepower: 1200,
    topSpeed: 321,
    range: 965,
    wingspan: 35,
    serviceCeiling: 33200
  },

  {
    name: 'folgore',
    id: 159,
    designation: 'mc-202',
    fullName: 'Macchi C.202 Folgore',
    manufacturer: 'Macchi',
    country: 'Italy',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1940,
    crew: 1,
    engineCount: 1,
    engine: 'Alfa Romeo RA.1000',
    horsepower: 1159,
    topSpeed: 372,
    range: 475,
    wingspan: 34.7,
    serviceCeiling: 37700
  },

  {
    name: 'veltro',
    id: 160,
    designation: 'mc-205',
    fullName: 'Macchi C.205 Veltro',
    manufacturer: 'Macchi',
    country: 'Italy',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'Fiat RA.1050 RC.58 Tifone',
    horsepower: 1455,
    topSpeed: 399,
    range: 590,
    wingspan: 34.7,
    serviceCeiling: 37700
  },

  {
    name: 'falco',
    id: 161,
    designation: 'cr-42',
    fullName: 'Fiat CR.42 Falco',
    manufacturer: 'Fiat',
    country: 'Italy',
    type: 'Biplane Fighter',
    role: 'Fighter / Attack',
    firstFlight: 1938,
    crew: 1,
    engineCount: 1,
    engine: 'Fiat A.74 RC38',
    horsepower: 840,
    topSpeed: 267,
    range: 485,
    wingspan: 31.8,
    serviceCeiling: 33400
  },

  {
    name: 'radesignationen',
    id: 162,
    designation: 'j2m',
    fullName: 'Mitsubishi J2M Radesignationen',
    manufacturer: 'Mitsubishi',
    country: 'Japan',
    type: 'Fighter',
    role: 'Land-based Interceptor',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'Mitsubishi Kasei 23',
    horsepower: 1820,
    topSpeed: 365,
    range: 1180,
    wingspan: 35.5,
    serviceCeiling: 38300
  },

  {
    name: 'george',
    id: 163,
    designation: 'n1k',
    fullName: 'Kawanishi N1K-J Shdesignationen',
    manufacturer: 'Kawanishi',
    country: 'Japan',
    type: 'Fighter',
    role: 'Land-based Interceptor',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'Nakajima Homare 21',
    horsepower: 1990,
    topSpeed: 369,
    range: 1065,
    wingspan: 39.3,
    serviceCeiling: 35400
  },

  {
    name: 'condor',
    id: 164,
    designation: 'fw-200',
    fullName: 'Fw 200 Condor',
    manufacturer: 'Focke-Wulf',
    country: 'Germany',
    type: 'Maritime Patrol',
    role: 'Long-range Recon / Bomber',
    firstFlight: 1937,
    crew: 5,
    engineCount: 4,
    engine: 'Bramo 323R-2',
    horsepower: 1200,
    topSpeed: 224,
    range: 2210,
    wingspan: 107.6,
    serviceCeiling: 19700
  },

  {
    name: 'hornisse',
    id: 165,
    designation: 'me-410',
    fullName: 'Me 410 Hornisse',
    manufacturer: 'Messerschmitt',
    country: 'Germany',
    type: 'Heavy Fighter',
    role: 'Zerstörer / Fast Bomber',
    firstFlight: 1942,
    crew: 2,
    engineCount: 2,
    engine: 'DB 603A',
    horsepower: 1726,
    topSpeed: 388,
    range: 1400,
    wingspan: 53.7,
    serviceCeiling: 32800
  },

  {
    name: 'blitz',
    id: 166,
    designation: 'ar-234',
    fullName: 'Arado Ar 234 Blitz',
    manufacturer: 'Arado',
    country: 'Germany',
    type: 'Jet Bomber',
    role: 'Reconnaissance / Bomber',
    firstFlight: 1943,
    crew: 1,
    engineCount: 2,
    engine: 'Junkers Jumo 004B',
    horsepower: null,
    topSpeed: 461,
    range: 965,
    wingspan: 46.3,
    serviceCeiling: 32800
  },

  {
    name: 'uhu',
    id: 167,
    designation: 'he-219',
    fullName: 'Heinkel He 219 Uhu',
    manufacturer: 'Heinkel',
    country: 'Germany',
    type: 'Heavy Fighter',
    role: 'Night Fighter',
    firstFlight: 1942,
    crew: 2,
    engineCount: 2,
    engine: 'DB 603E',
    horsepower: 1874,
    topSpeed: 416,
    range: 1240,
    wingspan: 60.7,
    serviceCeiling: 40000
  },

  {
    name: 'yak9',
    id: 168,
    designation: 'yak-9',
    fullName: 'Yakovlev Yak-9',
    manufacturer: 'Yakovlev',
    country: 'USSR',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'Klimov VK-105PF',
    horsepower: 1180,
    topSpeed: 373,
    range: 845,
    wingspan: 31.9,
    serviceCeiling: 30000
  },

  {
    name: 'tu2',
    id: 169,
    designation: 'tu-2',
    fullName: 'Tupolev Tu-2',
    manufacturer: 'Tupolev',
    country: 'USSR',
    type: 'Bomber',
    role: 'Medium Bomber',
    firstFlight: 1941,
    crew: 4,
    engineCount: 2,
    engine: 'Shvetsov ASh-82',
    horsepower: 1850,
    topSpeed: 328,
    range: 1255,
    wingspan: 61.8,
    serviceCeiling: 29500
  },

  {
    name: 'blenheim',
    id: 170,
    designation: 'blenheim',
    fullName: 'Bristol Blenheim',
    manufacturer: 'Bristol Aeroplane Company',
    country: 'UK',
    type: 'Bomber',
    role: 'Light Bomber / Night Fighter',
    firstFlight: 1935,
    crew: 3,
    engineCount: 2,
    engine: 'Bristol Mercury XV',
    horsepower: 920,
    topSpeed: 266,
    range: 1460,
    wingspan: 56.3,
    serviceCeiling: 27260
  },

  {
    name: 'halifax',
    id: 171,
    designation: 'halifax',
    fullName: 'Handley Page Halifax',
    manufacturer: 'Handley Page',
    country: 'UK',
    type: 'Bomber',
    role: 'Heavy Bomber',
    firstFlight: 1939,
    crew: 7,
    engineCount: 4,
    engine: 'Bristol Hercules XVI',
    horsepower: 1615,
    topSpeed: 282,
    range: 1860,
    wingspan: 104.2,
    serviceCeiling: 24000
  },

  {
    name: 'stirling',
    id: 172,
    designation: 'stirling',
    fullName: 'Short Stirling',
    manufacturer: 'Short Brothers',
    country: 'UK',
    type: 'Bomber',
    role: 'Heavy Bomber',
    firstFlight: 1939,
    crew: 7,
    engineCount: 4,
    engine: 'Bristol Hercules XI',
    horsepower: 1650,
    topSpeed: 282,
    range: 2330,
    wingspan: 99.1,
    serviceCeiling: 16500
  },

  {
    name: 'defiant',
    id: 173,
    designation: 'defiant',
    fullName: 'Boulton Paul Defiant',
    manufacturer: 'Boulton Paul Aircraft',
    country: 'UK',
    type: 'Fighter',
    role: 'Turret Fighter',
    firstFlight: 1937,
    crew: 2,
    engineCount: 1,
    engine: 'Rolls-Royce Merlin III',
    horsepower: 1030,
    topSpeed: 304,
    range: 465,
    wingspan: 39.3,
    serviceCeiling: 31000
  },

  {
    name: 'starfire',
    id: 174,
    designation: 'f-94',
    fullName: 'F-94 Starfire',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Interceptor',
    role: 'All-Weather Interceptor',
    firstFlight: 1949,
    crew: 2,
    engineCount: 1,
    engine: 'Pratt & Whitney J48',
    horsepower: null,
    topSpeed: 640,
    range: 805,
    wingspan: 37.4,
    serviceCeiling: 51400
  },

  {
    name: 'deltaDagger',
    id: 175,
    designation: 'f-102',
    fullName: 'F-102 Delta Dagger',
    manufacturer: 'Convair',
    country: 'USA',
    type: 'Interceptor',
    role: 'All-Weather Interceptor',
    firstFlight: 1953,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney J57',
    horsepower: null,
    topSpeed: 825,
    range: 1350,
    wingspan: 38.1,
    serviceCeiling: 53400
  },

  {
    name: 'vigilante',
    id: 176,
    designation: 'a-5',
    fullName: 'A-5 Vigilante',
    manufacturer: 'North American Aviation',
    country: 'USA',
    type: 'Bomber',
    role: 'Carrier-based Strike / Recon',
    firstFlight: 1958,
    crew: 2,
    engineCount: 2,
    engine: 'General Electric J79',
    horsepower: null,
    topSpeed: 1320,
    range: 1800,
    wingspan: 53,
    serviceCeiling: 52100
  },

  {
    name: 'skywarrior',
    id: 177,
    designation: 'a-3',
    fullName: 'A-3 Skywarrior',
    manufacturer: 'Douglas',
    country: 'USA',
    type: 'Bomber',
    role: 'Strategic Bomber',
    firstFlight: 1952,
    crew: 3,
    engineCount: 2,
    engine: 'Pratt & Whitney J57',
    horsepower: null,
    topSpeed: 610,
    range: 2100,
    wingspan: 72.5,
    serviceCeiling: 41000
  },

  {
    name: 'orion',
    id: 178,
    designation: 'p-3',
    fullName: 'P-3 Orion',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Maritime Patrol',
    role: 'Anti-Submarine Warfare',
    firstFlight: 1959,
    crew: 11,
    engineCount: 4,
    engine: 'Allison T56',
    horsepower: 4600,
    topSpeed: 466,
    range: 5570,
    wingspan: 99.7,
    serviceCeiling: 34000
  },

  {
    name: 'posedesignationon',
    id: 179,
    designation: 'p-8',
    fullName: 'P-8 Posedesignationon',
    manufacturer: 'Boeing',
    country: 'USA',
    type: 'Maritime Patrol',
    role: 'Anti-Submarine / Anti-Surface Warfare',
    firstFlight: 2009,
    crew: 9,
    engineCount: 2,
    engine: 'CFM International CFM56-7B',
    horsepower: null,
    topSpeed: 564,
    range: 4500,
    wingspan: 123.6,
    serviceCeiling: 41000
  },

  {
    name: 'buccaneer',
    id: 180,
    designation: 'buccaneer',
    fullName: 'Blackburn Buccaneer',
    manufacturer: 'Blackburn Aircraft',
    country: 'UK',
    type: 'Strike Aircraft',
    role: 'Maritime Strike',
    firstFlight: 1958,
    crew: 2,
    engineCount: 2,
    engine: 'Rolls-Royce Spey',
    horsepower: null,
    topSpeed: 669,
    range: 2300,
    wingspan: 43.3,
    serviceCeiling: 40000
  },

  {
    name: 'jaguar',
    id: 181,
    designation: 'jaguar',
    fullName: 'SEPECAT Jaguar',
    manufacturer: 'SEPECAT',
    country: 'Europe',
    type: 'Strike Aircraft',
    role: 'Close Air Support / Strike',
    firstFlight: 1968,
    crew: 1,
    engineCount: 2,
    engine: 'Rolls-Royce Turbomeca Adour',
    horsepower: null,
    topSpeed: 1056,
    range: 2190,
    wingspan: 28.5,
    serviceCeiling: 45900
  },

  {
    name: 'mirageF1',
    id: 182,
    designation: 'mirage',
    variant: 'F1',
    fullName: 'Mirage F1',
    manufacturer: 'Dassault Aviation',
    country: 'France',
    type: 'Fighter',
    role: 'Air Superiority / Attack',
    firstFlight: 1966,
    crew: 1,
    engineCount: 1,
    engine: 'Snecma Atar 9K-50',
    horsepower: null,
    topSpeed: 1453,
    range: 2050,
    wingspan: 27.5,
    serviceCeiling: 65600
  },

  {
    name: 'badger',
    id: 183,
    designation: 'tu-16',
    fullName: 'Tupolev Tu-16',
    manufacturer: 'Tupolev',
    country: 'USSR',
    type: 'Bomber',
    role: 'Strategic Bomber',
    firstFlight: 1952,
    crew: 6,
    engineCount: 2,
    engine: 'Mikulin AM-3',
    horsepower: null,
    topSpeed: 652,
    range: 4470,
    wingspan: 108.3,
    serviceCeiling: 41900
  },

  {
    name: 'backfire',
    id: 184,
    designation: 'tu-22',
    variant: 'M',
    fullName: 'Tupolev Tu-22M',
    manufacturer: 'Tupolev',
    country: 'USSR',
    type: 'Bomber',
    role: 'Strategic Strike Bomber',
    firstFlight: 1969,
    crew: 4,
    engineCount: 2,
    engine: 'Kuznetsov NK-25',
    horsepower: null,
    topSpeed: 1240,
    range: 4200,
    wingspan: 112.5,
    serviceCeiling: 43000
  }
];

export default airplanes;
